package w13_guiATM;

/**
 *
 * @author arrenbryan
 */
public class MenuPenarikanTunai extends javax.swing.JFrame implements IConfig {

    private Account account;

    public MenuPenarikanTunai(Account account) {
        this.account = account;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlBackground = new javax.swing.JPanel();
        PnlUtamaATM = new javax.swing.JPanel();
        LblPilihNominal = new javax.swing.JLabel();
        LblPilihJmlNominal = new javax.swing.JLabel();
        LblNominal1M = new javax.swing.JLabel();
        LblNominal1_5M = new javax.swing.JLabel();
        LblNominal2M = new javax.swing.JLabel();
        LblNominalLain = new javax.swing.JLabel();
        LblNominal200K = new javax.swing.JLabel();
        LblNominal100K = new javax.swing.JLabel();
        LblNominal300K = new javax.swing.JLabel();
        LblNominal500K = new javax.swing.JLabel();
        BtnNominal1M = new javax.swing.JButton();
        BtnNominal1_5M = new javax.swing.JButton();
        BtnNominal2M = new javax.swing.JButton();
        BtnNominalLain = new javax.swing.JButton();
        BtnNominal100K = new javax.swing.JButton();
        BtnNominal200K = new javax.swing.JButton();
        BtnNominal300K = new javax.swing.JButton();
        BtnNominal500K = new javax.swing.JButton();
        PnlPadATM = new javax.swing.JPanel();
        BtnPad1 = new javax.swing.JButton();
        BtnPad2 = new javax.swing.JButton();
        BtnPad3 = new javax.swing.JButton();
        BtnPad4 = new javax.swing.JButton();
        BtnPad5 = new javax.swing.JButton();
        BtnPad7 = new javax.swing.JButton();
        BtnPad6 = new javax.swing.JButton();
        BtnPad8 = new javax.swing.JButton();
        BtnPad9 = new javax.swing.JButton();
        BtnPad0 = new javax.swing.JButton();
        BtnPadClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Automated Teller Machine (ATM BRI)");

        PnlBackground.setBackground(new java.awt.Color(0, 0, 255));

        PnlUtamaATM.setBackground(new java.awt.Color(0, 35, 225));
        PnlUtamaATM.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        LblPilihNominal.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        LblPilihNominal.setForeground(java.awt.Color.white);
        LblPilihNominal.setText("SILAKAN PILIH");

        LblPilihJmlNominal.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        LblPilihJmlNominal.setForeground(java.awt.Color.white);
        LblPilihJmlNominal.setText("JUMLAH YANG DIINGINKAN");

        LblNominal1M.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        LblNominal1M.setForeground(java.awt.Color.white);
        LblNominal1M.setText("1.000.000 ==>");

        LblNominal1_5M.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        LblNominal1_5M.setForeground(java.awt.Color.white);
        LblNominal1_5M.setText("1.500.000 ==>");

        LblNominal2M.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        LblNominal2M.setForeground(java.awt.Color.white);
        LblNominal2M.setText("2.000.000 ==>");

        LblNominalLain.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        LblNominalLain.setForeground(java.awt.Color.white);
        LblNominalLain.setText("NOMINAL LAIN==>");

        LblNominal200K.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        LblNominal200K.setForeground(java.awt.Color.white);
        LblNominal200K.setText("<== 200.000");

        LblNominal100K.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        LblNominal100K.setForeground(java.awt.Color.white);
        LblNominal100K.setText("<== 100.000");

        LblNominal300K.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        LblNominal300K.setForeground(java.awt.Color.white);
        LblNominal300K.setText("<== 300.000");

        LblNominal500K.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        LblNominal500K.setForeground(java.awt.Color.white);
        LblNominal500K.setText("<== 500.000");

        javax.swing.GroupLayout PnlUtamaATMLayout = new javax.swing.GroupLayout(PnlUtamaATM);
        PnlUtamaATM.setLayout(PnlUtamaATMLayout);
        PnlUtamaATMLayout.setHorizontalGroup(
            PnlUtamaATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlUtamaATMLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(PnlUtamaATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlUtamaATMLayout.createSequentialGroup()
                        .addGap(0, 174, Short.MAX_VALUE)
                        .addComponent(LblPilihNominal)
                        .addGap(177, 177, 177))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlUtamaATMLayout.createSequentialGroup()
                        .addGroup(PnlUtamaATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblNominal1M, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlUtamaATMLayout.createSequentialGroup()
                                .addGroup(PnlUtamaATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LblNominal100K)
                                    .addComponent(LblNominal200K))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LblNominal1_5M))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlUtamaATMLayout.createSequentialGroup()
                                .addComponent(LblNominal300K)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LblNominal2M)))
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlUtamaATMLayout.createSequentialGroup()
                        .addComponent(LblNominal500K)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LblNominalLain)
                        .addGap(15, 15, 15))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlUtamaATMLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LblPilihJmlNominal)
                .addGap(134, 134, 134))
        );
        PnlUtamaATMLayout.setVerticalGroup(
            PnlUtamaATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlUtamaATMLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(LblPilihNominal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblPilihJmlNominal)
                .addGap(18, 18, 18)
                .addGroup(PnlUtamaATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlUtamaATMLayout.createSequentialGroup()
                        .addComponent(LblNominal1M)
                        .addGap(30, 30, 30)
                        .addComponent(LblNominal1_5M))
                    .addGroup(PnlUtamaATMLayout.createSequentialGroup()
                        .addComponent(LblNominal100K)
                        .addGap(30, 30, 30)
                        .addComponent(LblNominal200K)))
                .addGap(30, 30, 30)
                .addGroup(PnlUtamaATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblNominal2M)
                    .addComponent(LblNominal300K))
                .addGap(30, 30, 30)
                .addGroup(PnlUtamaATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblNominalLain)
                    .addComponent(LblNominal500K))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        BtnNominal1M.setForeground(java.awt.Color.lightGray);
        BtnNominal1M.setBorder(null);
        BtnNominal1M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNominal1MActionPerformed(evt);
            }
        });

        BtnNominal1_5M.setForeground(java.awt.Color.lightGray);
        BtnNominal1_5M.setBorder(null);
        BtnNominal1_5M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNominal1_5MActionPerformed(evt);
            }
        });

        BtnNominal2M.setForeground(java.awt.Color.lightGray);
        BtnNominal2M.setBorder(null);
        BtnNominal2M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNominal2MActionPerformed(evt);
            }
        });

        BtnNominalLain.setForeground(java.awt.Color.lightGray);
        BtnNominalLain.setBorder(null);
        BtnNominalLain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNominalLainActionPerformed(evt);
            }
        });

        BtnNominal100K.setForeground(java.awt.Color.lightGray);
        BtnNominal100K.setBorder(null);
        BtnNominal100K.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNominal100KActionPerformed(evt);
            }
        });

        BtnNominal200K.setForeground(java.awt.Color.lightGray);
        BtnNominal200K.setBorder(null);
        BtnNominal200K.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNominal200KActionPerformed(evt);
            }
        });

        BtnNominal300K.setForeground(java.awt.Color.lightGray);
        BtnNominal300K.setBorder(null);
        BtnNominal300K.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNominal300KActionPerformed(evt);
            }
        });

        BtnNominal500K.setForeground(java.awt.Color.lightGray);
        BtnNominal500K.setBorder(null);
        BtnNominal500K.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNominal500KActionPerformed(evt);
            }
        });

        PnlPadATM.setBackground(java.awt.Color.white);
        PnlPadATM.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        BtnPad1.setBackground(java.awt.Color.lightGray);
        BtnPad1.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        BtnPad1.setText("1");

        BtnPad2.setBackground(java.awt.Color.lightGray);
        BtnPad2.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        BtnPad2.setText("2");

        BtnPad3.setBackground(java.awt.Color.lightGray);
        BtnPad3.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        BtnPad3.setText("3");

        BtnPad4.setBackground(java.awt.Color.lightGray);
        BtnPad4.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        BtnPad4.setText("4");
        BtnPad4.setToolTipText("");

        BtnPad5.setBackground(java.awt.Color.lightGray);
        BtnPad5.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        BtnPad5.setText("5");
        BtnPad5.setToolTipText("");

        BtnPad7.setBackground(java.awt.Color.lightGray);
        BtnPad7.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        BtnPad7.setText("7");
        BtnPad7.setToolTipText("");

        BtnPad6.setBackground(java.awt.Color.lightGray);
        BtnPad6.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        BtnPad6.setText("6");
        BtnPad6.setToolTipText("");

        BtnPad8.setBackground(java.awt.Color.lightGray);
        BtnPad8.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        BtnPad8.setText("8");
        BtnPad8.setToolTipText("");

        BtnPad9.setBackground(java.awt.Color.lightGray);
        BtnPad9.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        BtnPad9.setText("9");
        BtnPad9.setToolTipText("");

        BtnPad0.setBackground(java.awt.Color.lightGray);
        BtnPad0.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        BtnPad0.setText("0");
        BtnPad0.setToolTipText("");

        BtnPadClear.setBackground(java.awt.Color.lightGray);
        BtnPadClear.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        BtnPadClear.setText("Clear");
        BtnPadClear.setToolTipText("");

        javax.swing.GroupLayout PnlPadATMLayout = new javax.swing.GroupLayout(PnlPadATM);
        PnlPadATM.setLayout(PnlPadATMLayout);
        PnlPadATMLayout.setHorizontalGroup(
            PnlPadATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlPadATMLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(PnlPadATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PnlPadATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PnlPadATMLayout.createSequentialGroup()
                            .addComponent(BtnPad7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(BtnPad8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(BtnPad9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PnlPadATMLayout.createSequentialGroup()
                            .addComponent(BtnPad4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(BtnPad5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(BtnPad6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PnlPadATMLayout.createSequentialGroup()
                            .addComponent(BtnPad1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(BtnPad2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(BtnPad3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PnlPadATMLayout.createSequentialGroup()
                        .addComponent(BtnPad0, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnPadClear, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        PnlPadATMLayout.setVerticalGroup(
            PnlPadATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlPadATMLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(PnlPadATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnPad1)
                    .addComponent(BtnPad2)
                    .addComponent(BtnPad3))
                .addGap(18, 18, 18)
                .addGroup(PnlPadATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnPad4)
                    .addComponent(BtnPad5)
                    .addComponent(BtnPad6))
                .addGap(18, 18, 18)
                .addGroup(PnlPadATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnPad7)
                    .addComponent(BtnPad8)
                    .addComponent(BtnPad9))
                .addGap(18, 18, 18)
                .addGroup(PnlPadATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnPad0)
                    .addComponent(BtnPadClear))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PnlBackgroundLayout = new javax.swing.GroupLayout(PnlBackground);
        PnlBackground.setLayout(PnlBackgroundLayout);
        PnlBackgroundLayout.setHorizontalGroup(
            PnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlBackgroundLayout.createSequentialGroup()
                .addGroup(PnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlBackgroundLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(PnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(BtnNominal200K, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BtnNominal300K, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(BtnNominal500K, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlBackgroundLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BtnNominal100K, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PnlUtamaATM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnNominal1M, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(BtnNominal1_5M, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnNominalLain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnNominal2M, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlBackgroundLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PnlPadATM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
        );
        PnlBackgroundLayout.setVerticalGroup(
            PnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlBackgroundLayout.createSequentialGroup()
                .addGroup(PnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlBackgroundLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(BtnNominal1M, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnNominal1_5M, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnNominal2M, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnNominalLain, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PnlBackgroundLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(PnlUtamaATM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PnlBackgroundLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(BtnNominal100K, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnNominal200K, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnNominal300K, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnNominal500K, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addComponent(PnlPadATM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnNominal100KActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNominal100KActionPerformed
        validateBalance(100_000);
    }//GEN-LAST:event_BtnNominal100KActionPerformed

    private void BtnNominal200KActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNominal200KActionPerformed
        validateBalance(200_000);
    }//GEN-LAST:event_BtnNominal200KActionPerformed

    private void BtnNominal300KActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNominal300KActionPerformed
        validateBalance(300_000);
    }//GEN-LAST:event_BtnNominal300KActionPerformed

    private void BtnNominal500KActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNominal500KActionPerformed
        validateBalance(500_000);
    }//GEN-LAST:event_BtnNominal500KActionPerformed

    private void BtnNominal1MActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNominal1MActionPerformed
        validateBalance(1_000_000);
    }//GEN-LAST:event_BtnNominal1MActionPerformed

    private void BtnNominal1_5MActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNominal1_5MActionPerformed
        validateBalance(1_500_000);
    }//GEN-LAST:event_BtnNominal1_5MActionPerformed

    private void BtnNominal2MActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNominal2MActionPerformed
        validateBalance(2_000_000);
    }//GEN-LAST:event_BtnNominal2MActionPerformed

    private void BtnNominalLainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNominalLainActionPerformed
        MenuInputNominalPenarikan mn_inputPenarikan = new MenuInputNominalPenarikan(account);
        mn_inputPenarikan.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnNominalLainActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnNominal100K;
    private javax.swing.JButton BtnNominal1M;
    private javax.swing.JButton BtnNominal1_5M;
    private javax.swing.JButton BtnNominal200K;
    private javax.swing.JButton BtnNominal2M;
    private javax.swing.JButton BtnNominal300K;
    private javax.swing.JButton BtnNominal500K;
    private javax.swing.JButton BtnNominalLain;
    private javax.swing.JButton BtnPad0;
    private javax.swing.JButton BtnPad1;
    private javax.swing.JButton BtnPad2;
    private javax.swing.JButton BtnPad3;
    private javax.swing.JButton BtnPad4;
    private javax.swing.JButton BtnPad5;
    private javax.swing.JButton BtnPad6;
    private javax.swing.JButton BtnPad7;
    private javax.swing.JButton BtnPad8;
    private javax.swing.JButton BtnPad9;
    private javax.swing.JButton BtnPadClear;
    private javax.swing.JLabel LblNominal100K;
    private javax.swing.JLabel LblNominal1M;
    private javax.swing.JLabel LblNominal1_5M;
    private javax.swing.JLabel LblNominal200K;
    private javax.swing.JLabel LblNominal2M;
    private javax.swing.JLabel LblNominal300K;
    private javax.swing.JLabel LblNominal500K;
    private javax.swing.JLabel LblNominalLain;
    private javax.swing.JLabel LblPilihJmlNominal;
    private javax.swing.JLabel LblPilihNominal;
    private javax.swing.JPanel PnlBackground;
    private javax.swing.JPanel PnlPadATM;
    private javax.swing.JPanel PnlUtamaATM;
    // End of variables declaration//GEN-END:variables

    private boolean isBalanceAvailable(int nominal) {
        return account.getAccountBalance() - SALDOMINIMALATM >= nominal;
    }

    private void validateBalance(int nominal) {
        if (isBalanceAvailable(nominal)) {
            updateBalance(nominal);
            MenuMelakukanTransaksiLain mn_transaksiLain = new MenuMelakukanTransaksiLain(account);
            mn_transaksiLain.setVisible(true);
            this.dispose();
        } else {
            System.err.println("Penarikan tunai gagal, uang tidak mencukupi!");
            this.dispose();
        }
    }

    private void updateBalance(int nominal) {
        account.setAccountBalance(account.getAccountBalance() - nominal);
        Account[] accountList = IJsonParse.deserializeAccount();
        for (int i = 0; i <= accountList.length - 1; i++) {
            if (account.getAccountNumber().equals(accountList[i].getAccountNumber())) {
                accountList[i].setAccountBalance(account.getAccountBalance());
                break;
            }
        }

        IJsonParse.serializeAccount(accountList);
    }
}
